Add error on CI when SPM_NAME is nil

diff --git a/.github/workflows/buildAndTest.yml b/.github/workflows/buildAndTest.yml
--- a/.github/workflows/buildAndTest.yml
+++ b/.github/workflows/buildAndTest.yml
@@ -3,7 +3,6 @@ on:
   workflow_call
     
 env:
-  spm_path: ${{ vars.SPM_PATH && '/' || '' }}
   spm_name: ${{ vars.SPM_NAME }}-Package
   swift_version: '5.9'
   xcode_path: "/Applications/Xcode_15.0.1.app"
@@ -17,7 +16,13 @@ jobs:
     runs-on: macos-14
     steps:
     - name: "Package name"
-      run: echo "Build ${{ env.spm_path }}${{ env.spm_name }} SPM"
+      run: |
+        if [ "${{ vars.SPM_NAME }}" != '' ]; then
+          echo "Build ${{ env.spm_name }} SPM at ${{ github.workspace }}"
+        else
+          echo "::error::SPM_NAME variable is NOT set on the repository settings"
+          exit 1
+        fi
     - name: Set Swift Version
       uses: swift-actions/setup-swift@v1
       with:
@@ -38,7 +43,13 @@ jobs:
     runs-on: macos-14
     steps:
     - name: "Package name"
-      run: echo "Build ${{ env.spm_name }} SPM at ${{ github.workspace }}"
+      run: |
+        if [ "${{ vars.SPM_NAME }}" != '' ]; then
+          echo "Build ${{ env.spm_name }} SPM at ${{ github.workspace }}"
+        else
+          echo "::error file=app.js,line=1::Missing semicolon"
+          exit 1
+        fi
     - name: Set Swift Version
       uses: swift-actions/setup-swift@v1
       with:
